CRAFTAX_MAX_RETURN = 226.0

CRAFTAX_ACHIEVEMENT_KEYS = (

    # Tier 0 - Basic
    "Achievements/wake_up",
    "Achievements/collect_wood",
    "Achievements/collect_stone",
    "Achievements/collect_sapling",
    "Achievements/collect_drink",
    "Achievements/collect_coal",
    "Achievements/collect_iron",
    "Achievements/collect_diamond",
    "Achievements/place_table",
    "Achievements/place_plant",
    "Achievements/place_stone",
    "Achievements/place_furnace",
    "Achievements/place_torch",
    "Achievements/make_wood_pickaxe",
    "Achievements/make_wood_sword",
    "Achievements/make_stone_pickaxe",
    "Achievements/make_stone_sword",
    "Achievements/make_iron_pickaxe",
    "Achievements/make_iron_sword",
    "Achievements/make_arrow",
    "Achievements/make_torch",
    "Achievements/eat_cow",
    "Achievements/eat_plant",
    "Achievements/defeat_zombie",
    "Achievements/defeat_skeleton",

    # Tier 1 - Intermediate
    "Achievements/make_iron_armour",
    "Achievements/make_diamond_pickaxe",
    "Achievements/make_diamond_sword",
    "Achievements/make_diamond_armour",
    "Achievements/enter_gnomish_mines",
    "Achievements/enter_dungeon",
    "Achievements/defeat_gnome_warrior",
    "Achievements/defeat_gnome_archer",
    "Achievements/defeat_orc_solider",
    "Achievements/defeat_orc_mage",
    "Achievements/eat_bat",
    "Achievements/eat_snail",
    "Achievements/find_bow",
    "Achievements/fire_bow",
    "Achievements/collect_sapphire",
    "Achievements/collect_ruby",
    "Achievements/open_chest",
    "Achievements/drink_potion",

    # Tier 2 - Advanced
    "Achievements/enter_sewers",
    "Achievements/enter_vault",
    "Achievements/enter_troll_mines",
    "Achievements/defeat_lizard",
    "Achievements/defeat_kobold",
    "Achievements/defeat_troll",
    "Achievements/defeat_deep_thing",
    "Achievements/defeat_knight",
    "Achievements/defeat_archer",
    "Achievements/learn_fireball",
    "Achievements/cast_fireball",
    "Achievements/learn_iceball",
    "Achievements/cast_iceball",
    "Achievements/enchant_sword",
    "Achievements/enchant_armour",

    # Tier 3 - Very Advanced
    "Achievements/enter_fire_realm",
    "Achievements/enter_ice_realm",
    "Achievements/enter_graveyard",
    "Achievements/defeat_pigman",
    "Achievements/defeat_fire_elemental",
    "Achievements/defeat_frost_troll",
    "Achievements/defeat_ice_elemental",
    "Achievements/damage_necromancer",
    "Achievements/defeat_necromancer",
)

def action_id_to_name(action_id: int) -> str:
    # From Craftax paper, Table 5 (IDs 0–42).
    action_names = [
        "NOOP",
        "LEFT",
        "RIGHT",
        "UP",
        "DOWN",
        "DO",
        "SLEEP",
        "PLACE_STONE",
        "PLACE_TABLE",
        "PLACE_FURNACE",
        "PLACE_PLANT",
        "MAKE_WOOD_PICKAXE",
        "MAKE_STONE_PICKAXE",
        "MAKE_IRON_PICKAXE",
        "MAKE_WOOD_SWORD",
        "MAKE_STONE_SWORD",
        "MAKE_IRON_SWORD",
        "REST",
        "DESCEND",
        "ASCEND",
        "MAKE_DIAMOND_PICKAXE",
        "MAKE_DIAMOND_SWORD",
        "MAKE_IRON_ARMOUR",
        "MAKE_DIAMOND_ARMOUR",
        "SHOOT_ARROW",
        "MAKE_ARROW",
        "CAST_FIREBALL",
        "CAST_ICEBALL",
        "PLACE_TORCH",
        "DRINK_POTION_RED",
        "DRINK_POTION_GREEN",
        "DRINK_POTION_BLUE",
        "DRINK_POTION_PINK",
        "DRINK_POTION_CYAN",
        "DRINK_POTION_YELLOW",
        "READ_BOOK",
        "ENCHANT_SWORD",
        "ENCHANT_ARMOUR",
        "MAKE_TORCH",
        "LEVEL_UP_DEXTERITY",
        "LEVEL_UP_STRENGTH",
        "LEVEL_UP_INTELLIGENCE",
        "ENCHANT_BOW"
    ]

    if 0 <= action_id < len(action_names):
        return action_names[action_id]
    return f"UNKNOWN_{action_id}"